const products={
 'comedor-160':{type:'Comedor / Entrega inmediata',title:'Comedor para 6 personas',availability:'Disponible para entrega inmediata',regular:'$16,500',cash:'$14,000',label:'Precio de contado con descuento',note:'15% de descuento en compras de contado. Mercancía en exhibición y sobre pedido.',facts:[['Medidas de mesa','1.20 m × 1.60 m'],['Financiamiento','Hasta 3 o 6 meses con tarjeta']],images:['catalog-comedor-160.jpg','catalog-comedor-160-detail.jpg']},
 'sala-modular':{type:'Sala / Entrega inmediata',title:'Sala modular con 2 reclinables',availability:'Disponible para entrega inmediata',regular:'$22,500',cash:'$17,500',label:'Precio especial de contado',note:'15% de descuento en compras de contado. El precio especial aplica únicamente en mercancía en existencia.',facts:[['Medidas','3.00 m × 3.00 m'],['Financiamiento','3 o 6 meses con tarjeta']],images:['catalog-sala-modular-main.jpg','catalog-sala-modular-detail.jpg','catalog-sala-modular-recliner.jpg']},
 'comedor-100':{type:'Comedor / Entrega inmediata',title:'Comedor para 6 personas',availability:'Disponible para entrega inmediata',regular:'$14,400',cash:'$12,200',label:'Precio de contado con descuento',note:'15% de descuento en compras de contado. Mercancía en exhibición y sobre pedido.',facts:[['Medidas de mesa','1.00 m × 1.60 m'],['Financiamiento','Hasta 3 o 6 meses con tarjeta']],images:['catalog-comedor-100.jpg','catalog-comedor-100-detail.jpg']},
 'bufetero':{type:'Bufetero / Entrega inmediata',title:'Bufetero de madera oscura',availability:'Disponible para entrega inmediata',regular:'$5,100',cash:'$4,300',label:'Precio especial de contado',note:'15% de descuento en compras de contado.',facts:[['Medidas','90 cm alto × 1.50 m ancho × 40 cm fondo']],images:['catalog-bufetero-main.jpg','catalog-bufetero-detail.jpg']},
 'comedor-180':{type:'Comedor / Entrega inmediata',title:'Comedor para 6 personas',availability:'Disponible para entrega inmediata',regular:'$16,000',cash:'$13,600',label:'Precio de contado con descuento',note:'15% de descuento en compras de contado. Mercancía en exhibición y sobre pedido.',facts:[['Medidas de mesa','1.10 m × 1.80 m'],['Financiamiento','Hasta 3 o 6 meses con tarjeta']],images:['catalog-comedor-180.jpg','catalog-comedor-180-detail.jpg']},
 'sala-esquinera':{type:'Sala / Entrega inmediata',title:'Sala tipo escuadra con 2 reclinables',availability:'Disponible para entrega inmediata',regular:'$18,500',cash:'$14,500',label:'Precio especial de contado',note:'15% de descuento en compras de contado. El precio especial aplica únicamente en mercancía en existencia.',facts:[['Medidas','2.20 m × 2.90 m'],['Financiamiento','3 o 6 meses con tarjeta bancaria']],images:['catalog-sala-esquinera.jpg']}
};
const $=s=>document.querySelector(s);const slug=new URLSearchParams(location.search).get('product')||location.pathname.split('/').filter(Boolean).pop();const p=products[slug];
if(p){document.title=`${p.title} | El Faraón Decoración & Muebles`; $('[data-detail-type]').textContent=p.type;$('[data-detail-title]').textContent=p.title;$('[data-detail-availability]').textContent=p.availability;$('[data-detail-regular]').textContent=`Precio regular ${p.regular}`;$('[data-detail-cash]').textContent=p.cash;$('[data-detail-cash-label]').textContent=p.label;$('[data-detail-note]').textContent=p.note;$('[data-detail-facts]').innerHTML=p.facts.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');const main=$('[data-detail-main]'), thumbs=$('[data-detail-thumbs]');p.images.forEach((file,i)=>{const src=`/public/assets/${file}`;if(i===0){main.src=src;main.alt=p.title}const b=document.createElement('button');b.type='button';b.className=i===0?'active':'';b.setAttribute('aria-label',`Ver imagen ${i+1}`);b.innerHTML=`<img src="${src}" alt="">`;b.onclick=()=>{main.src=src;thumbs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active')};thumbs.append(b)})}else{$('[data-detail-title]').textContent='Modelo no encontrado';$('[data-detail-note]').textContent='Regresa al catálogo para elegir otra pieza.'}
